#!/usr/bin/env bash

_rofi () {
    rofi -dmenu -i -no-levenshtein-sort -width 1000 "$@"
}

# display settings
display_type=1
max_str_width=80

# keybindings
switch_view="Alt+Tab"
new_bookmark="Alt+n"
actions="Alt+a"
edit="Alt+e"
delete="Alt+d"

# colors
help_color="#334433"

# source global config
if [[ -f /etc/rofi-buku.config ]]
then
  source /etc/rofi-buku.config
fi

# source local config:
if [[ -z $XDG_CONFIG_DIR ]]
then
  if [[ -f $HOME/.config/rofi-buku/config ]]
  then
    source $HOME/.config/rofi-buku/config
  else
    echo "User config file '~/.config/rofi-buku/config' not found. using global config"
  fi
else
  if [[ -f "${XDG_CONFIG_DIR}/rofi-buku/config" ]]
  then
    source "${XDG_CONFIG_DIR}/rofi-buku/config"
  else
    echo "User config file '~/.config/rofi-buku/config' not found. using global config"
  fi
fi


main () {
    HELP="Welcome to Buku. Use <span color='${help_color}'>${new_bookmark}</span> to add a new Bookmark
Use <span color='${help_color}'>${switch_view}</span> to switch View. <span color='${help_color}'>${actions}</span> for actions"
    if [[ $mode == "bookmarks" ]]; then
        content=$(parseBuku) 
		filteredContent=$(
			if [ "$filter" = "" ]; then
				printf '%s' "$content"
			else
				awk -F'  +' -v tag="$filter" '
				{
					n = split($3, a, ",")
					for (i = 1; i <= n; i++) {
						gsub(/^ +| +$/, "", a[i])
						if (a[i] == tag) { print; break }
						}
				}
			' <<< "$content"
						fi
					)

        menu=$(echo "${filteredContent}" | _rofi -p '> ' -filter "" -mesg "${HELP}" -kb-custom-1 "${new_bookmark}" -kb-custom-2 "${switch_view}" -kb-custom-3 "${actions}" -kb-custom-4 "${edit}" -kb-custom-5 "${delete}")
    elif [[ $mode == "tags" ]]; then
		menu="$(buku --nostdin --np --st |
			grep -v -e '^waiting for input$' -e '^$' |
			awk '{$NF=""; sub(/[[:space:]]+$/,""); print}' |
			cut -d ' ' -f2- |
			_rofi -p '> ' -mesg "${HELP}" \
			-kb-custom-1 "${new_bookmark}" \
			-kb-custom-2 "${switch_view}" \
			-kb-custom-3 "${actions}" \
			-kb-custom-4 "${edit}" \
			-kb-custom-5 "${delete}")"
    fi
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 12 ]]; then
        optionsMenu
    elif [[ $val -eq 10 ]]; then
        addMark
    elif [[ $val -eq 14 ]]; then
        deleteMenu
    elif [[ $val -eq 13 ]]; then
        editMenu
    elif [[ $val -eq 11 ]]; then
        if [[ $mode == "bookmarks" ]]; then
            export mode="tags"
            mode=tags main
        elif [[ $mode == "tags" ]]; then
            export mode="bookmarks"
			export filter=""
            mode=bookmarks main
        fi
    elif [[ $val -eq 0 ]]; then
        if [[ $mode == "bookmarks" ]]; then
            id=$(getId "$content" "$menu")
			url="$(getUrlFromId "${id}")"
			echo -n "$url" | xclip -sel c && notify-send "Bookmark copied to clipboard"
            # for bm in ${id}; do
            #     buku --nostdin -o "${bm}"
            # done
        elif [[ $mode == "tags" ]]; then
            filter="${menu}" mode="bookmarks" main
        fi
    fi
}

optionsMenu () {
  if [[ $mode == "bookmarks" ]]; then
    askmenu=$(echo -e "< Return\\n---\\n1. Edit\\n2. Delete" | _rofi -p '> ' -mesg "Choose Action for bookmark")
    val=$?

    if [[ $val -eq 1 ]]; then
      exit
    elif [[ $val -eq 0 ]]; then
      if [[ $askmenu == "< Return" ]]; then
        export mode=bookmarks
        main
      elif [[ $askmenu == "1. Edit" ]]; then
        editMenu
      elif [[ $askmenu == "2. Delete" ]]; then
        deleteMenu
      fi
    fi
  elif [[ $mode == "tags" ]]; then
    askmenu=$(echo -e "< Return\\n---\\n1. Replace Tag\\n2. Delete Tag" | _rofi -p '> ' -mesg "Choose Action for tag \"${menu}\"")
    val=$?

    if [[ $val -eq 1 ]]; then
      exit
    elif [[ $val -eq 0 ]]; then
      if [[ $askmenu == "< Return" ]]; then
        export mode=tags
        main
      elif [[ $askmenu == "1. Replace Tag" ]]; then
        newtag=$(echo | _rofi -p '> ' -mesg "Enter new tag name for tag \"${menu}\"")
        val=$?

        if [[ $val -eq 1 ]]; then
          exit
        elif [[ $val -eq 0 ]]; then
          if [[ $newtag == "" ]]; then
            mode=tags main
          else
            buku --nostdin --replace "${menu}" "${newtag}"
            mode=tags main
          fi
        fi
      elif [[ $askmenu == "2. Delete Tag" ]]; then
        delask=$(echo -e "1. Yes\\n2. No" | _rofi -p '> ' -mesg "Really delete tag \"${menu}\" from ALL bookmarks?")
        val=$?

        if [[ $val -eq 1 ]]; then
          exit
        elif [[ $val -eq 0 ]]; then
          if [[ $delask == "1. Yes" ]]; then
	    echo y | script -qfc "buku --nostdin --replace ${menu}" /dev/null
            mode=tags main
          elif [[ $delask == "2. No" ]]; then
            mode=tags main
          fi
        fi
      fi
    fi
  fi
}

deleteMenu () {
  id=$(getId "$content" "$menu")

  delask=$(echo -e "1. Yes\\n2. No" | _rofi -p '> ' -mesg "Really delete bookmark?")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    if [[ $delask == "1. Yes" ]]; then
      buku --nostdin -d "${id}" --tacit
      mode=bookmarks main
    elif [[ $delask == "2. No" ]]; then
      optionsMenu
    fi
  fi
}

editMenu () {
    id=$(getId "$content" "$menu")

	json="$(getJsonFromId "${id}")"

	eval "$(jq -r '
	"title=\(.title|@sh)
	url=\(.uri|@sh)
	comment=\(.description|@sh)
	tags=\(.tags|@sh)"' <<<"$json")"

    content="1. Title: $title\\n2. URL: $url\\n3. Comment: $comment\\n4. Tags: $tags"
    editmenu=$(echo -e "< Return\\n---\\n${content}" | _rofi -p '> ')
    val=$?

    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        if [[ $editmenu == "< Return" ]]; then
            main
        elif [[ $editmenu =~ Title:* ]]; then
            editTitle
        elif [[ $editmenu =~ URL:* ]]; then
            editUrl
        elif [[ $editmenu =~ Comment:* ]]; then
            editComment
        elif [[ $editmenu =~ Tags:* ]]; then
            editTags
        fi
    fi
}

editTitle () {
  titlemenu=$(echo "" | _rofi -p "> " -filter "${title}" -mesg "Edit Title and hit Enter")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    buku --nostdin -u "${id}" --title "${titlemenu}"
  fi

  mode=bookmarks main
}

editUrl () {
  urlmenu=$(echo "" | _rofi -p "> " -filter "${url}" -mesg "Edit URL and hit Enter")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    if [[ $urlmenu != "http"* ]]; then
      echo "" | rofi -e "Not a valid URI, Make sure URLs start with http"
      editUrl
    else
      buku --nostdin -u "${id}" --url "${urlmenu}"
    fi
  fi

  mode=bookmarks main
}

editComment () {
  commentmenu=$(echo "" | _rofi -p "> " -filter "${comment}" -mesg "Edit Comment and hit Enter")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    buku --nostdin -u "${id}" --comment "${commentmenu}"
  fi

  mode=bookmarks main
}

editTags () {
  edittagsmenu=$(echo | _rofi -filter "${tags}" -p '> ' -mesg "Edit Tags and hit Enter")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    buku --nostdin -u "${id}" --tag "${edittagsmenu}"
  fi

  mode=bookmarks main
}

addMark () {
  inserturl=$(echo -e "$(xclip -o)" | _rofi -p '> ' -mesg "Use URL below or type manually")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    addTags
  fi
}

addTags () {
  inserttags=$(buku --nostdin --np --st | grep -v '^waiting for input$' | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "Add some tags. Separate tags with ', '")
  val=$?

  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    if [[ $(echo "${inserttags}" | wc -l) -gt 1 ]]; then
      taglist=$(echo "${inserttags}" | tr '\n' ',')
      tags=()
      for tag in $taglist; do
        tags+=("$tag")
      done
    else
      tags=${inserttags}
    fi

    buku --nostdin -a "${inserturl}" "${tags}" --immutable 1
  fi
}

parseBuku () {

  buku --nostdin --nc -p -f 4 |
    grep -v '^waiting for input$' |
    gawk -v max="$max_str_width" -v type="$display_type" '
      BEGIN { FS="\t"; OFS="\t" }

      function trim(s) {
        sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); return s
      }

      {
        id    = trim($1)
        url   = trim($2)
        title = trim($3)
        tags  = (NF >= 4) ? trim($4) : "NOTAG"

        if (max+0 > 0) {
          if (length(title) > max) title = substr(title, 1, max-1) "…"
          if (length(url)   > max) url   = substr(url,   1, max-1) "…"
        }

        if (type == 1)      # id, title, tags
          print id, title, tags

        else if (type == 2) # id, title, tags (duplicate of type 1 in the old script)
          print id, title, tags

        else if (type == 3) # id, title, url, tags
          print id, title, url, tags

        else                # fallback: show everything
          print id, title, url, tags

        print ""
      }
    ' |
    column -t -s $'\t'
}

getId () {
  id="${2%% *}"
  if [ -z "$id" ]; then
    prev=""
    IFS=$'\n'
    for line in $1; do
      if [ "$2" = "$line" ]; then
        id="${prev%% *}"
        break
      else
        prev="$line"
      fi
    done
  fi
  echo $id
}

getJsonFromId () {
	echo "$(buku --nostdin --nc -p "${1}" --json)"
}

getUrlFromId () {
  buku --nostdin --nc -p "${1}" | grep -v '^waiting for input$' | gawk '
    BEGIN { RS=""; FS="\n" }

    { print gensub(/\s+> (.*)/, "\\1", "g", $2) }
  '
}

mode=tags main
